/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error-container": "#93000a",
        "tertiary-fixed": "#ebe2c8",
        "on-tertiary-fixed": "#1f1c0b",
        "on-tertiary-fixed-variant": "#4c4733",
        "surface-variant": "#e3e2e0",
        "inverse-surface": "#2f312f",
        "on-primary": "#ffffff",
        "primary-fixed-dim": "#c1c6d7",
        "on-secondary": "#ffffff",
        "on-surface": "#1a1c1a",
        "primary-fixed": "#dde2f3",
        "on-primary-fixed": "#161c27",
        background: "#faf9f6",
        "on-surface-variant": "#45474c",
        "outline-variant": "#c6c6cc",
        "on-tertiary-container": "#8e8770",
        outline: "#76777c",
        "on-background": "#1a1c1a",
        "surface-dim": "#dbdad7",
        "secondary-container": "#ffca98",
        error: "#ba1a1a",
        tertiary: "#0b0800",
        "on-secondary-container": "#7a532a",
        "inverse-primary": "#c1c6d7",
        "surface-container": "#efeeeb",
        "secondary-fixed-dim": "#f0bd8b",
        "tertiary-fixed-dim": "#cec6ad",
        "error-container": "#ffdad6",
        "secondary-fixed": "#ffdcbd",
        "surface-container-low": "#f4f3f1",
        "on-secondary-fixed": "#2c1600",
        "surface-container-highest": "#e3e2e0",
        secondary: "#7d562d",
        "surface-tint": "#585e6c",
        "on-primary-container": "#828796",
        "surface-container-high": "#e9e8e5",
        "on-tertiary": "#ffffff",
        "primary-container": "#1a202c",
        "on-secondary-fixed-variant": "#623f18",
        "tertiary-container": "#24200f",
        "on-error": "#ffffff",
        surface: "#faf9f6",
        "surface-bright": "#faf9f6",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed-variant": "#414754",
        primary: "#030813",
        "inverse-on-surface": "#f2f1ee",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        unit: "8px",
        gutter: "32px",
        "section-gap": "120px",
        "margin-desktop": "80px",
        "margin-mobile": "24px",
      },
      fontFamily: {
        "body-lg": ['"Source Serif 4"'],
        "label-md": ["Montserrat"],
        "display-lg": ["Montserrat"],
        "headline-sm": ["Montserrat"],
        "headline-md": ["Montserrat"],
        "body-md": ['"Source Serif 4"'],
        "display-lg-mobile": ["Montserrat"],
      },
      fontSize: {
        "body-lg": ["20px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "600" }],
        "display-lg": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-sm": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-lg-mobile": ["40px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
};
